name: libro_diario_app
description: "Una aplicación para gestionar un libro diario contable de forma interactiva."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Ajustado para compatibilidad amplia

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Backend y Autenticación)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  # Gestión de Estado (Bloc)
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5 

  # Ruteo / Navegación
  go_router: ^13.2.0

  # Exportación y Gráficos
  excel: ^2.1.0 
  fl_chart: ^0.66.2
  
  # Utilidades
  intl: ^0.19.0 

  # Iconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Versión compatible

flutter:
  uses-material-design: true
